INSERT INTO categories (name) VALUES ('dairy');
INSERT INTO categories (name) VALUES ('produce');
INSERT INTO categories (name) VALUES ('meat');
INSERT INTO categories (name) VALUES ('bread/bakery');
INSERT INTO categories (name) VALUES ('frozen');
INSERT INTO categories (name) VALUES ('packaged/dry goods');
INSERT INTO categories (name) VALUES ('other');

INSERT INTO items (name, cat_id) VALUES ('milk', 1);
INSERT INTO items (name, cat_id) VALUES ('creamer', 1);
INSERT INTO items (name, cat_id) VALUES ('cheese', 1);
INSERT INTO items (name, cat_id) VALUES ('butter', 1);
INSERT INTO items (name, cat_id) VALUES ('sour cream', 1);
INSERT INTO items (name, cat_id) VALUES ('cream cheese', 1);
INSERT INTO items (name, cat_id) VALUES ('yogurt', 1);

INSERT INTO items (name, cat_id) VALUES ('apples', 2);
INSERT INTO items (name, cat_id) VALUES ('oranges', 2);
INSERT INTO items (name, cat_id) VALUES ('lemons', 2);
INSERT INTO items (name, cat_id) VALUES ('limes', 2);
INSERT INTO items (name, cat_id) VALUES ('lettuce', 2);
INSERT INTO items (name, cat_id) VALUES ('avocados', 2);
INSERT INTO items (name, cat_id) VALUES ('bananas', 2);
INSERT INTO items (name, cat_id) VALUES ('celery', 2);
INSERT INTO items (name, cat_id) VALUES ('cucumbers', 2);
INSERT INTO items (name, cat_id) VALUES ('carrots', 2);
INSERT INTO items (name, cat_id) VALUES ('broccoli', 2);
INSERT INTO items (name, cat_id) VALUES ('tomatoes', 2);

INSERT INTO items (name, cat_id) VALUES ('chicken breast', 3);
INSERT INTO items (name, cat_id) VALUES ('ground turkey', 3);
INSERT INTO items (name, cat_id) VALUES ('ground beef', 3);
INSERT INTO items (name, cat_id) VALUES ('steak', 3);
INSERT INTO items (name, cat_id) VALUES ('deli turkey', 3);
INSERT INTO items (name, cat_id) VALUES ('deli ham', 3);
INSERT INTO items (name, cat_id) VALUES ('salami', 3);
INSERT INTO items (name, cat_id) VALUES ('chicken wings', 3);
INSERT INTO items (name, cat_id) VALUES ('pork chops', 3);

INSERT INTO items (name, cat_id) VALUES ('white bread', 4);
INSERT INTO items (name, cat_id) VALUES ('whole grain bread', 4);
INSERT INTO items (name, cat_id) VALUES ('rye bread', 4);
INSERT INTO items (name, cat_id) VALUES ('tortillas', 4);
INSERT INTO items (name, cat_id) VALUES ('bagels', 4);
INSERT INTO items (name, cat_id) VALUES ('muffins', 4);
INSERT INTO items (name, cat_id) VALUES ('bagette', 4);
INSERT INTO items (name, cat_id) VALUES ('donuts', 4);
INSERT INTO items (name, cat_id) VALUES ('english muffins', 4);

INSERT INTO items (name, cat_id) VALUES ('frozen broccoli', 5);
INSERT INTO items (name, cat_id) VALUES ('frozen carrots', 5);
INSERT INTO items (name, cat_id) VALUES ('frozen corn', 5);
INSERT INTO items (name, cat_id) VALUES ('frozen green beans', 5);
INSERT INTO items (name, cat_id) VALUES ('frozen strawberries', 5);
INSERT INTO items (name, cat_id) VALUES ('frozen blueberries', 5);
INSERT INTO items (name, cat_id) VALUES ('assorted frozen fruit', 5);
INSERT INTO items (name, cat_id) VALUES ('chicken nuggets', 5);
INSERT INTO items (name, cat_id) VALUES ('french fries', 5);
INSERT INTO items (name, cat_id) VALUES ('tater tots', 5);
INSERT INTO items (name, cat_id) VALUES ('waffles', 5);
INSERT INTO items (name, cat_id) VALUES ('icecream', 5);
INSERT INTO items (name, cat_id) VALUES ('white bread', 5);

INSERT INTO items (name, cat_id) VALUES ('flour', 6);
INSERT INTO items (name, cat_id) VALUES ('sugar', 6);
INSERT INTO items (name, cat_id) VALUES ('cereal', 6);
INSERT INTO items (name, cat_id) VALUES ('brown sugar', 6);
INSERT INTO items (name, cat_id) VALUES ('pasta', 6);
INSERT INTO items (name, cat_id) VALUES ('rice', 6);
INSERT INTO items (name, cat_id) VALUES ('baking powder', 6);
INSERT INTO items (name, cat_id) VALUES ('baking soda', 6);
INSERT INTO items (name, cat_id) VALUES ('olive oil', 6);
INSERT INTO items (name, cat_id) VALUES ('crackers', 6);

INSERT INTO items (name, cat_id) VALUES ('toilet paper', 7);
INSERT INTO items (name, cat_id) VALUES ('tin foil', 7);
INSERT INTO items (name, cat_id) VALUES ('paper plates', 7);
INSERT INTO items (name, cat_id) VALUES ('paper towels', 7);
INSERT INTO items (name, cat_id) VALUES ('cat food', 7);
INSERT INTO items (name, cat_id) VALUES ('dog food', 7);
INSERT INTO items (name, cat_id) VALUES ('cat treats', 7);
INSERT INTO items (name, cat_id) VALUES ('dog treats', 7);